### ISSUE TITLE
Pick a bot framework already.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/Xythrion#1]
- [discord.js](https://github.com/discordjs/discord.js)
- [discord.py](https://github.com/Rapptz/discord.py)
- [serenity](https://github.com/serenity-rs/serenity)

**Comment by chethanyadav456** [comment]
Discord.js

**Comment by Xithrius** [comment]
Perhaps.

**Comment by chethanyadav456** [comment]
> Perhaps.

Because it supports api v10

**Comment by Xithrius** [comment]
How did you find this issue lol

**Comment by Xithrius** [comment]
I have decided on [disnake](https://github.com/DisnakeDev/disnake).
