### ISSUE TITLE
Source command

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/Xythrion#7]
Continuation of https://github.com/Xithrius/Xythrion-legacy/issues/8

@fisher60 I'm giving you a second chance. Dew it in `xythrion/extensions/meta/source.py`, thanks.

**Comment by fisher60** [comment]
I accept

**Comment by Xithrius** [comment]
Thanks.

**Comment by Xithrius** [comment]
@fisher60 when

**Comment by Xithrius** [comment]
perhaps not
