### ISSUE TITLE
Creating the source cog.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/Xythrion#8]
Creating the source command will be somewhat hard, as there are no current functions in the bot to search for cogs/commands.

- [ ] Source
    - [ ] Cog
    - [ ] Help command
    - [ ] Singular command

**Comment by lantrungseo** [comment]
Hi there, I would like to work on these issue in **hacktoberfest**. I really appreciate if you can assign me to this issue.

P/S: what is cog?

**Comment by Xithrius** [comment]
@lantrungseo Hello, thank you for having an interest in this issue!

I'll be assigning you this, but I think it would be easier to just search for the lines of commands first and then move on to entire cogs.

Cogs are basically the classes the commands are residing in, as you can see in the extensions folder. You can think of a Cog as an extension of the class `discord.ext.commands.Bot`, subclassed [here](https://github.com/Xithrius/Xythrion/blob/master/xythrion/bot.py#L17).

If a person searches for a cog such as "Graphing", it should show them [this](https://github.com/Xithrius/Xythrion/blob/master/xythrion/extensions/generation/graphing.py#L10-L39). If a person searches for a single command such as "graph", it should return [this link](https://github.com/Xithrius/Xythrion/blob/master/xythrion/extensions/generation/graphing.py#L21-L39).

When creating the source cog, I'd place it in `xythrion/extensions/meta/source.py`, importing the cog within the `__init__.py` file of the same directory to include it in the setup function.

**Comment by lantrungseo** [comment]
Since now I have too many tasks at hand, I am sorry to announce that I could not continue to contribute to your project despite my initial interest. I hope that you could find another contributor in replace of me. 

P/S: Maybe in the future, I could come back here again.

**Comment by fisher60** [comment]
Hello, I would like to attempt a speedrun for this.

**Comment by Xithrius** [comment]
@fisher60 go ahead.
